version: "2"

services:
  frontend:
    container_name: "personal_website"
    build: .
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app